### ISSUE TITLE
Invalid particle creation

### ISSUE THREAD

**Issue by jklae** [jklee95/GridLiquid2D#17]
**Describe the bug**
I just found a terrible bug. The particle creation location was wrong. (Rows and columns are reversed)
This will probably cause problems everywhere index function is used.

**Screenshots**
<image src="https://user-images.githubusercontent.com/44741178/139255804-aac7736e-e94a-4123-ac1c-04d65c90fbc8.png" width="50%" height="50%">

**Comment by jklee95** [comment]
This issue was completely resolved by repositioning loops i and j in commit 41eaffdc20d4a54331f4c009248792a5f2870eae.
